

INSERT INTO users (role, id, activation_url, city, country, latitude, longitude, street_and_num, username,rating, enabled, last_name, last_password_reset_date, name, password, phone_num,reason_for_deleting,current_points,rank_type, is_predefined, registration_reason) values ('FISHINGINSTRUCTOR',4,null, 'Novi Sad','Serbia',45.267136,19.833549, 'ULICA','fi@gmail.com', 4.5,true, 'Filip','2022-01-04 15:31:53.899','Jovanovic','$2a$04$Vbug2lwwJGrvUXTj6z7ff.97IzVBkrJ1XfApfGNl.Z695zqcnPYra','+3810616789856','',0,0,null,'Da zaradim malo iako ne znam da pecam.');
INSERT INTO users (role, id, activation_url, city, country, latitude, longitude, street_and_num, username,rating, enabled, last_name, last_password_reset_date, name, password, phone_num,reason_for_deleting,current_points,rank_type, is_predefined, registration_reason) values ('FISHINGINSTRUCTOR',9,null, 'Beograd','Serbia',45.267136,19.833549, 'ULICA','fi2@gmail.com', 4.5,true, 'Marko','2022-01-04 15:31:53.899','Petrovic','$2a$04$Vbug2lwwJGrvUXTj6z7ff.97IzVBkrJ1XfApfGNl.Z695zqcnPYra','+3810616789856','',0,0,null,'Da zaradim malo iako ne znam da pecam.');

INSERT INTO adventure (id, city, country, latitude, longitude, street_and_num, canceling_condition, description, equipment, instructors_biography, max_people, name, price, rules, users_id) VALUES (1, 'Kovin ', 'Serbia', 21.1158834777415, 44.74496215218308, 'Dunavska 3', 'NOT FREE', 'The best adventure.', 'Hooks, lines, sinkers, floats, rods, reels, baits, lures, spears, nets.', 'Licensed fishing instructor with 30 years of experience.', 5, 'Gepard fish adventure', 200, 'No non-swimmers.', 4);
INSERT INTO adventure (id, city, country, latitude, longitude, street_and_num, canceling_condition, description, equipment, instructors_biography, max_people, name, price, rules, users_id) VALUES (2, 'Kostolac', 'Serbia', 21.16904786256799, 44.71575022220559, 'Dunavska 7A', 'FREE', 'Fishing classes safe for kids.', 'Hooks, lines, sinkers, floats, rods, reels, baits.', 'Licensed fishing instructor with 30 years of experience.', 10, 'Teaching kids how to fish', 150, 'No special rules.', 4);
INSERT INTO adventure (id, city, country, latitude, longitude, street_and_num, canceling_condition, description, equipment, instructors_biography, max_people, name, price, rules, users_id) VALUES (3, 'Bajina Basta ', 'Serbia', 19.396795367345533, 43.88933175347052, 'Zaovine', 'FREE', 'Fun adventure for all ages.', 'Hooks, lines, sinkers, floats.', 'Licensed instructor. ', 3, 'Carp Fishing Tour', 70, 'No non-swimmers. No kids.', 9);
INSERT INTO adventure (id, city, country, latitude, longitude, street_and_num, canceling_condition, description, equipment, instructors_biography, max_people, name, price, rules, users_id) VALUES (4, 'Smederevo ', 'Serbia', 20.933046702303997, 44.671871390896925, 'Djure Strugara 5', 'FREE', 'The most visited adventure.', 'Reels, baits, lures, spears, nets, gaffs.', 'Liscensed fishing instructor.', 10, 'Familly fishing', 100, 'No rules.', 9);

